### ISSUE TITLE
Is it possible to read/fetch added customised token in metamask in react?

### ISSUE THREAD

**Issue by aditim121** [MetaMask/Add-Token#36]
I am trying to add ERC20 token to metamask from react js. First time it gets added. But whenever I refresh the page it asks to re-add the token. Is there a way to check the token is already added.

If its already added it should not promt user to add the token. 
Is there a way to code this in react?

**Comment by Gudahtt** [comment]
There is no way for a website to discover the user's token list in MetaMask at the moment, no.

I'm assuming from that description that you're adding the token during page load? Instead move it to an "Add token" button, so the prompt only shows up when the button is clicked. Popups during page load tend to irritate users.
